[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip stm32u083rctx --catch-reset --catch-hardfault"

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "trace"
