[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip stm32u083rctx --catch-hardfault --always-print-stacktrace --connect-under-reset --speed 950"

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "trace"
